version: '3.7'

services:
  order-service:
    container_name: order-service
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file: 
      .development.env
     
