export const FIRST_THREE_KILOMETER_FEE = 15000;
export const EXTRA_KILOMETER_FEE = 5000;
export const FIRST_SHIPPING_KILOMETER = 3000;
export const PERCENT_PLATFORM_FEE = 0.05;
export const DEFAULT_EXCHANGE_RATE = 0.00004;
