export enum DeliveryStatus {
  DRAFT = 'DRAFT',
  ASSIGNING_DRIVER = 'ASSIGNING_DRIVER',
  ON_GOING = 'ON_GOING ',
  PICKED_UP = 'PICKED_UP',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
