export enum DeliveryIssue {
  ITEM_IS_OUT_OF_STOCK = 'ITEM_IS_OUT_OF_STOCK',
  RESTAURANT_CLOSED = 'RESTAURANT_CLOSED',
  CANNOT_ASSIGN_DRIVER = 'CANNOT_ASSIGN_DRIVER',
  CANNOT_BUY_ORDER = 'CANNOT_BUY_ORDER',
}
