export enum PaymentStatus {
  PENDING_USER_ACTION = 'PENDING_USER_ACTION',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  REFUNDED = 'REFUNDED',
  PENDING_REFUNDED = 'PENDING_REFUNDED',
  CANCELLED = 'CANCELLED',
}
